export const adminUser = {
  fullName: 'JewelAura Admin',
  email: 'admin@jewelaura.vn',
  password: 'Admin@123',
  phone: '0901234567',
  address: '25 Anh Kim, Quan 1, TP. Ho Chi Minh',
  role: 'admin'
};

export const sampleUsers = [
  {
    fullName: 'Nguyen Minh Chau',
    email: 'chau@jewelaura.vn',
    password: 'User@123',
    phone: '0905678123',
    address: 'Quan 3, TP. Ho Chi Minh',
    role: 'user'
  },
  {
    fullName: 'Tran Hoang An',
    email: 'an@jewelaura.vn',
    password: 'User@123',
    phone: '0912345678',
    address: 'Quan Hai Chau, Da Nang',
    role: 'user'
  },
  {
    fullName: 'Le Bao Nhi',
    email: 'nhi@jewelaura.vn',
    password: 'User@123',
    phone: '0987654321',
    address: 'Quan Ninh Kieu, Can Tho',
    role: 'user'
  }
];

export const categories = [
  {
    name: 'Nhẫn',
    slug: 'nhan',
    description: 'Nhung mau nhan thanh lich danh cho qua tang va su dung hang ngay.',
    image: '/images/categories/nhan.jpg',
    status: 'active'
  },
  {
    name: 'Day chuyen',
    slug: 'day-chuyen',
    description: 'Day chuyen toi gian va sang trong cho nhieu phong cach.',
    image: '/images/categories/day-chuyen.jpg',
    status: 'active'
  },
  {
    name: 'Bong tai',
    slug: 'bong-tai',
    description: 'Bong tai nhe va tinh te de ket hop cung trang phuc hien dai.',
    image: '/images/categories/bong-tai.jpg',
    status: 'active'
  },
  {
    name: 'Lac tay',
    slug: 'lac-tay',
    description: 'Lac tay thanh manh lam diem nhan cho co tay.',
    image: '/images/categories/lac-tay.jpg',
    status: 'active'
  },
  {
    name: 'Vong co',
    slug: 'vong-co',
    description: 'Vong co cao cap voi thiet ke no bat va de phoi do.',
    image: '/images/categories/vong-co.jpg',
    status: 'active'
  },
  {
    name: 'Trang suc cuoi',
    slug: 'trang-suc-cuoi',
    description: 'Bo suu tap danh cho ngay trong dai voi tinh than thanh lich.',
    image: '/images/categories/trang-suc-cuoi.jpg',
    status: 'active'
  },
  {
    name: 'Dong ho',
    slug: 'dong-ho',
    description: 'Dong ho thoi trang cao cap ket hop giua tinh chinh xac va tham my.',
    image: '/images/categories/dong-ho.jpg',
    status: 'active'
  }
];

export const coupons = [
  {
    code: 'WELCOME10',
    name: 'Chao mung khach moi',
    description: 'Giam 10% toi da 300.000 VND cho don tu 1.000.000 VND.',
    discountType: 'percentage',
    discountValue: 10,
    minOrderValue: 1000000,
    maxDiscountAmount: 300000,
    usageLimit: 200,
    usedCount: 0,
    startDate: new Date('2026-01-01T00:00:00.000Z'),
    endDate: new Date('2026-12-31T23:59:59.999Z'),
    isActive: true
  },
  {
    code: 'JEWEL500',
    name: 'Giam 500K',
    description: 'Giam truc tiep 500.000 VND cho don tu 5.000.000 VND.',
    discountType: 'fixed',
    discountValue: 500000,
    minOrderValue: 5000000,
    maxDiscountAmount: 0,
    usageLimit: 100,
    usedCount: 0,
    startDate: new Date('2026-01-01T00:00:00.000Z'),
    endDate: new Date('2026-12-31T23:59:59.999Z'),
    isActive: true
  },
  {
    code: 'FREESHIP',
    name: 'Ho tro phi giao hang',
    description: 'Giam 30.000 VND cho don tu 500.000 VND.',
    discountType: 'fixed',
    discountValue: 30000,
    minOrderValue: 500000,
    maxDiscountAmount: 0,
    usageLimit: 300,
    usedCount: 0,
    startDate: new Date('2026-01-01T00:00:00.000Z'),
    endDate: new Date('2026-12-31T23:59:59.999Z'),
    isActive: true
  }
];

export const homepageBanners = [
  {
    name: 'Banner dau trang 01',
    imageUrl: '/images/banners/home-banner-1.jpg',
    mobileImageUrl: '/images/banners/home-banner-1.jpg',
    title: 'Tuyen chon trang suc danh cho khoanh khac toa sang',
    subtitle: 'Bo suu tap moi voi nhan, day chuyen va qua tang duoc chon loc cho phong cach hien dai.',
    buttonLabel: 'Kham pha ngay',
    buttonLink: '/products',
    isActive: true
  },
  {
    name: 'Banner dau trang 02',
    imageUrl: '/images/banners/home-banner-2.jpg',
    mobileImageUrl: '/images/banners/home-banner-2.jpg',
    title: 'Diem nhan moi cho mua qua tang',
    subtitle: 'Ket hop chat lieu cao cap, bo cuc toi gian va trai nghiem mua sam ro rang.',
    buttonLabel: 'Xem san pham noi bat',
    buttonLink: '/products?featured=true',
    isActive: true
  },
  {
    name: 'Banner dau trang 03',
    imageUrl: '/images/banners/home-banner-3.jpg',
    mobileImageUrl: '/images/banners/home-banner-3.jpg',
    title: 'Bo suu tap moi len ke',
    subtitle: 'Cap nhat nhung mau vua ve danh cho khach hang muon kham pha nhanh xu huong moi.',
    buttonLabel: 'Xem hang moi',
    buttonLink: '/products?sort=newest',
    isActive: true
  }
];

export const homepageSections = [
  {
    key: 'top-banner',
    type: 'banner_slider',
    title: 'Banner chien dich',
    subtitle: 'Khu vuc banner lon cho homepage.',
    buttonLabel: '',
    buttonLink: '',
    isActive: true,
    order: 1,
    displayMode: 'hero'
  },
  {
    key: 'featured-categories',
    type: 'category_grid',
    title: 'Kham pha theo phong cach cua ban',
    subtitle: 'Cac nhom san pham duoc to chuc ro rang de hanh trinh mua sam tu nhien, cao cap va de chon hon.',
    buttonLabel: 'Xem toan bo san pham',
    buttonLink: '/products',
    isActive: true,
    order: 2,
    items: [
      {
        title: 'Nhan',
        subtitle: 'Thiet ke thanh lich cho phong cach hang ngay va nhung dip dac biet.',
        image: 'from-[#fdf4d7] via-[#fffdf8] to-[#efe3ba]',
        link: '/products?category=nhan'
      },
      {
        title: 'Bong tai',
        subtitle: 'Diem nhan gon gang, sang trong cho dien mao hien dai.',
        image: 'from-[#edf3fb] via-white to-[#dbe7f7]',
        link: '/products?category=bong-tai'
      },
      {
        title: 'Day chuyen',
        subtitle: 'Duong net mem mai, tinh te va de phoi trong nhieu hoan canh.',
        image: 'from-[#f7f0f5] via-white to-[#eadce7]',
        link: '/products?category=day-chuyen'
      },
      {
        title: 'Lac tay',
        subtitle: 'Cam giac nhe, nu tinh va cao cap cho co tay noi bat vua du.',
        image: 'from-[#eff8f2] via-white to-[#dceddf]',
        link: '/products?category=lac-tay'
      }
    ]
  },
  {
    key: 'featured-products',
    type: 'product_carousel',
    title: 'Lua chon duoc yeu thich',
    subtitle: 'Nhung thiet ke dang duoc quan tam nhieu nhat, cap nhat truc tiep tu du lieu san pham.',
    buttonLabel: 'Xem bo suu tap',
    buttonLink: '/products?featured=true',
    isActive: true,
    order: 3,
    displayMode: 'listing'
  },
  {
    key: 'editorial-grid',
    type: 'editorial_grid',
    title: 'Ve dep thanh lich cho moi khoanh khac',
    subtitle: 'Kham pha nhung thiet ke duoc chon loc cho ngay thuong, dip ky niem va nhung mon qua can su tinh te.',
    buttonLabel: 'Mua sam ngay',
    buttonLink: '/products',
    isActive: true,
    order: 4,
    items: [
      {
        title: 'Bridal Atelier',
        subtitle: 'Nhung thiet ke cuoi anh kim theo tinh than thanh lich, toi gian va vuot thoi gian.',
        badge: 'Danh cho ngay trong dai'
      },
      {
        title: 'Daily Signature',
        subtitle: 'Trang suc danh cho nhip song hien dai, can bang giua tinh te va kha nang ung dung.',
        badge: 'Phong cach thuong nhat'
      },
      {
        title: 'Gift Selection',
        subtitle: 'Tuyen chon qua tang sang trong voi ngon ngu thiet ke gon gang, de ghi dau an.',
        badge: 'Cho khoanh khac dang nho'
      }
    ]
  },
  {
    key: 'new-arrivals',
    type: 'product_carousel',
    title: 'Moi len ke',
    subtitle: 'Nhung thiet ke vua cap nhat, phu hop cho khach hang muon kham pha nhanh cac mau moi nhat.',
    buttonLabel: 'Xem san pham moi',
    buttonLink: '/products?sort=newest',
    isActive: true,
    order: 5,
    displayMode: 'compact'
  },
  {
    key: 'service-grid',
    type: 'service_grid',
    title: 'Trai nghiem mua sam ro rang va dang tin cay',
    subtitle: 'Moi diem cham duoc toi uu de tao cam giac mua sam nhu mot thuong hieu trang suc thuc thu.',
    buttonLabel: '',
    buttonLink: '',
    isActive: true,
    order: 6,
    items: [
      {
        title: 'Kiem dinh minh bach',
        subtitle: 'Thong tin chat lieu, trong luong va chi tiet san pham duoc trinh bay ro rang.'
      },
      {
        title: 'Doi size linh hoat',
        subtitle: 'Ho tro doi size trong thoi gian phu hop voi chinh sach cua JewelAura.'
      },
      {
        title: 'Dong goi sang trong',
        subtitle: 'Bao bi cao cap, chi chu de san sang cho ca tu thuong va qua tang.'
      },
      {
        title: 'Tu van ca nhan hoa',
        subtitle: 'De xuat san pham theo ngan sach, phong cach va dip su dung cu the.'
      }
    ]
  }
];

const rawProducts = [
  {
    name: 'Nhan vang 14K dinh da Aurora',
    slug: 'nhan-vang-14k-dinh-da-aurora',
    categorySlug: 'nhan',
    price: 4590000,
    oldPrice: 5200000,
    discount: 12,
    images: ['/images/products/ring-aurora-1.jpg', '/images/products/ring-aurora-2.jpg'],
    material: 'Vang 14K',
    stone: 'CZ trang',
    weight: 2.4,
    size: ['12', '13', '14', '15'],
    gender: 'Nu',
    stock: 18,
    sold: 42,
    isFeatured: true,
    status: 'active',
    description: 'Mau nhan mat da tron nho, de deo hang ngay va phu hop lam qua tang.'
  },
  {
    name: 'Nhan vang 18K dinh da Soleil',
    slug: 'nhan-vang-18k-dinh-da-soleil',
    categorySlug: 'nhan',
    price: 6890000,
    oldPrice: 7390000,
    discount: 7,
    images: ['/images/products/ring-soleil-1.jpg', '/images/products/ring-soleil-2.jpg'],
    material: 'Vang 18K',
    stone: 'Topaz vang',
    weight: 2.9,
    size: ['13', '14', '15', '16'],
    gender: 'Nu',
    stock: 12,
    sold: 25,
    isFeatured: true,
    status: 'active',
    description: 'Thiet ke banh mi thanh canh, ton tay va phu hop nhung dip dac biet.'
  },
  {
    name: 'Nhan bac dinh ngoc trai Luna',
    slug: 'nhan-bac-dinh-ngoc-trai-luna',
    categorySlug: 'nhan',
    price: 2190000,
    oldPrice: 2490000,
    discount: 12,
    images: ['/images/products/ring-luna-1.jpg', '/images/products/ring-luna-2.jpg'],
    material: 'Bac 925',
    stone: 'Ngoc trai nuoc ngot',
    weight: 2.1,
    size: ['11', '12', '13', '14'],
    gender: 'Nu',
    stock: 20,
    sold: 31,
    isFeatured: false,
    status: 'active',
    description: 'Nhan bac gam ngoc trai nho, mang lai cam giac nhe nhang va thanh tao.'
  },
  {
    name: 'Nhan doi Eternal Promise',
    slug: 'nhan-doi-eternal-promise',
    categorySlug: 'trang-suc-cuoi',
    price: 12900000,
    oldPrice: 13800000,
    discount: 6,
    images: ['/images/products/ring-eternal-1.jpg', '/images/products/ring-eternal-2.jpg'],
    material: 'Vang 18K',
    stone: 'Kim cuong tam',
    weight: 5.8,
    size: ['14', '15', '16', '17', '18'],
    gender: 'Unisex',
    stock: 8,
    sold: 16,
    isFeatured: true,
    status: 'active',
    description: 'Cap nhan doi toi gian voi duong net mem, phu hop cho le cuoi hien dai.'
  },
  {
    name: 'Nhan nam Titan Navy',
    slug: 'nhan-nam-titan-navy',
    categorySlug: 'nhan',
    price: 3290000,
    oldPrice: 3690000,
    discount: 10,
    images: ['/images/products/ring-navy-1.jpg', '/images/products/ring-navy-2.jpg'],
    material: 'Titanium ma vang',
    stone: 'Khong da',
    weight: 4.2,
    size: ['17', '18', '19', '20'],
    gender: 'Nam',
    stock: 14,
    sold: 19,
    isFeatured: false,
    status: 'active',
    description: 'Nhan nam ban rong, sac net va de ket hop voi phong cach cong so.'
  },
  {
    name: 'Day chuyen mat troi Celeste',
    slug: 'day-chuyen-mat-troi-celeste',
    categorySlug: 'day-chuyen',
    price: 3790000,
    oldPrice: 4290000,
    discount: 12,
    images: ['/images/products/necklace-celeste-1.jpg', '/images/products/necklace-celeste-2.jpg'],
    material: 'Vang 14K',
    stone: 'CZ champagne',
    weight: 3.1,
    size: ['40cm', '42cm', '45cm'],
    gender: 'Nu',
    stock: 16,
    sold: 37,
    isFeatured: true,
    status: 'active',
    description: 'Day chuyen mat troi nho, de phoi voi ao co V hoac dam da hoi.'
  },
  {
    name: 'Day chuyen ngoc trai Ocean Pearl',
    slug: 'day-chuyen-ngoc-trai-ocean-pearl',
    categorySlug: 'day-chuyen',
    price: 5590000,
    oldPrice: 5990000,
    discount: 7,
    images: ['/images/products/necklace-ocean-1.jpg', '/images/products/necklace-ocean-2.jpg'],
    material: 'Bac 925 ma vang',
    stone: 'Ngoc trai nuoc ngot',
    weight: 4.4,
    size: ['42cm', '45cm'],
    gender: 'Nu',
    stock: 11,
    sold: 22,
    isFeatured: true,
    status: 'active',
    description: 'Chuoi ngoc trai ket hop khoa vang nhe, tao diem nhan thanh lich.'
  },
  {
    name: 'Day chuyen layer Starlight',
    slug: 'day-chuyen-layer-starlight',
    categorySlug: 'day-chuyen',
    price: 2890000,
    oldPrice: 3290000,
    discount: 12,
    images: ['/images/products/necklace-starlight-1.jpg', '/images/products/necklace-starlight-2.jpg'],
    material: 'Bac 925',
    stone: 'CZ trang',
    weight: 3.6,
    size: ['38cm', '40cm', '42cm'],
    gender: 'Nu',
    stock: 19,
    sold: 28,
    isFeatured: false,
    status: 'active',
    description: 'Thiet ke layer hai tang tao hieu ung co thon gon va hien dai.'
  },
  {
    name: 'Day chuyen unisex Monogram',
    slug: 'day-chuyen-unisex-monogram',
    categorySlug: 'day-chuyen',
    price: 3190000,
    oldPrice: 3490000,
    discount: 9,
    images: ['/images/products/necklace-monogram-1.jpg', '/images/products/necklace-monogram-2.jpg'],
    material: 'Thep khong gi',
    stone: 'Khong da',
    weight: 5.1,
    size: ['50cm', '55cm'],
    gender: 'Unisex',
    stock: 24,
    sold: 18,
    isFeatured: false,
    status: 'active',
    description: 'Mau day chuyen mat thang don gian danh cho phong cach thanh lich toi gian.'
  },
  {
    name: 'Day chuyen kim cuong Grace',
    slug: 'day-chuyen-kim-cuong-grace',
    categorySlug: 'trang-suc-cuoi',
    price: 15800000,
    oldPrice: 16800000,
    discount: 6,
    images: ['/images/products/necklace-grace-1.jpg', '/images/products/necklace-grace-2.jpg'],
    material: 'Vang trang 18K',
    stone: 'Kim cuong tam',
    weight: 4.2,
    size: ['42cm', '45cm'],
    gender: 'Nu',
    stock: 7,
    sold: 11,
    isFeatured: true,
    status: 'active',
    description: 'Day chuyen mat giot nuoc gam da sang, phu hop trong tiec va su kien.'
  },
  {
    name: 'Bong tai hoa tuyet Crystal Bloom',
    slug: 'bong-tai-hoa-tuyet-crystal-bloom',
    categorySlug: 'bong-tai',
    price: 2690000,
    oldPrice: 2990000,
    discount: 10,
    images: ['/images/products/earring-bloom-1.jpg', '/images/products/earring-bloom-2.jpg'],
    material: 'Bac 925 ma vang',
    stone: 'CZ trang',
    weight: 1.8,
    size: ['Free'],
    gender: 'Nu',
    stock: 21,
    sold: 33,
    isFeatured: true,
    status: 'active',
    description: 'Bong tai dang hoa nho giup guong mat sang va de phoi do.'
  },
  {
    name: 'Bong tai ngoc trai Ivory',
    slug: 'bong-tai-ngoc-trai-ivory',
    categorySlug: 'bong-tai',
    price: 2390000,
    oldPrice: 2690000,
    discount: 11,
    images: ['/images/products/earring-ivory-1.jpg', '/images/products/earring-ivory-2.jpg'],
    material: 'Bac 925',
    stone: 'Ngoc trai nuoc ngot',
    weight: 1.6,
    size: ['Free'],
    gender: 'Nu',
    stock: 18,
    sold: 27,
    isFeatured: false,
    status: 'active',
    description: 'Thiet ke dang nut toi gian, phu hop moi ngay va nhieu do tuoi.'
  },
  {
    name: 'Bong tai vuong Emerald Edge',
    slug: 'bong-tai-vuong-emerald-edge',
    categorySlug: 'bong-tai',
    price: 3490000,
    oldPrice: 3890000,
    discount: 10,
    images: ['/images/products/earring-emerald-1.jpg', '/images/products/earring-emerald-2.jpg'],
    material: 'Vang 14K',
    stone: 'CZ xanh luc',
    weight: 2.0,
    size: ['Free'],
    gender: 'Nu',
    stock: 14,
    sold: 14,
    isFeatured: false,
    status: 'active',
    description: 'Bong tai hinh vuong nho tao diem nhan ca tinh nhung van tinh te.'
  },
  {
    name: 'Bong tai treo Golden Drop',
    slug: 'bong-tai-treo-golden-drop',
    categorySlug: 'bong-tai',
    price: 4290000,
    oldPrice: 4690000,
    discount: 9,
    images: ['/images/products/earring-golden-drop-1.jpg', '/images/products/earring-golden-drop-2.jpg'],
    material: 'Vang 18K',
    stone: 'Thach anh vang',
    weight: 2.5,
    size: ['Free'],
    gender: 'Nu',
    stock: 10,
    sold: 12,
    isFeatured: true,
    status: 'active',
    description: 'Dang treo thanh canh, thich hop cho buoi toi va set do thanh lich.'
  },
  {
    name: 'Bong tai nam Onyx Bar',
    slug: 'bong-tai-nam-onyx-bar',
    categorySlug: 'bong-tai',
    price: 1990000,
    oldPrice: 2290000,
    discount: 13,
    images: ['/images/products/earring-onyx-1.jpg', '/images/products/earring-onyx-2.jpg'],
    material: 'Thep khong gi',
    stone: 'Onyx den',
    weight: 1.4,
    size: ['Free'],
    gender: 'Nam',
    stock: 17,
    sold: 20,
    isFeatured: false,
    status: 'active',
    description: 'Bong tai don chiec dang thanh, gon va hop phong cach nam hien dai.'
  },
  {
    name: 'Lac tay charm Aurora Line',
    slug: 'lac-tay-charm-aurora-line',
    categorySlug: 'lac-tay',
    price: 2590000,
    oldPrice: 2890000,
    discount: 10,
    images: ['/images/products/bracelet-aurora-1.jpg', '/images/products/bracelet-aurora-2.jpg'],
    material: 'Bac 925 ma vang',
    stone: 'CZ trang',
    weight: 3.0,
    size: ['15cm', '16cm', '17cm'],
    gender: 'Nu',
    stock: 22,
    sold: 24,
    isFeatured: false,
    status: 'active',
    description: 'Lac tay dang day manh co charm nho, mang lai cam giac tre trung.'
  },
  {
    name: 'Lac tay ngoc trai Soft Pearl',
    slug: 'lac-tay-ngoc-trai-soft-pearl',
    categorySlug: 'lac-tay',
    price: 3190000,
    oldPrice: 3590000,
    discount: 11,
    images: ['/images/products/bracelet-soft-pearl-1.jpg', '/images/products/bracelet-soft-pearl-2.jpg'],
    material: 'Bac 925',
    stone: 'Ngoc trai nuoc ngot',
    weight: 2.7,
    size: ['15cm', '16cm', '17cm'],
    gender: 'Nu',
    stock: 16,
    sold: 15,
    isFeatured: true,
    status: 'active',
    description: 'Mau lac tay xen ke ngoc trai nho va khoa tron thanh lich.'
  },
  {
    name: 'Lac tay xich nam Urban Steel',
    slug: 'lac-tay-xich-nam-urban-steel',
    categorySlug: 'lac-tay',
    price: 2890000,
    oldPrice: 3190000,
    discount: 9,
    images: ['/images/products/bracelet-urban-steel-1.jpg', '/images/products/bracelet-urban-steel-2.jpg'],
    material: 'Thep khong gi',
    stone: 'Khong da',
    weight: 6.3,
    size: ['18cm', '19cm', '20cm'],
    gender: 'Nam',
    stock: 13,
    sold: 17,
    isFeatured: false,
    status: 'active',
    description: 'Thiet ke xich ban vua tao diem nhan manh me cho co tay nam.'
  },
  {
    name: 'Lac tay da xanh Mint Shine',
    slug: 'lac-tay-da-xanh-mint-shine',
    categorySlug: 'lac-tay',
    price: 3390000,
    oldPrice: 3790000,
    discount: 10,
    images: ['/images/products/bracelet-mint-shine-1.jpg', '/images/products/bracelet-mint-shine-2.jpg'],
    material: 'Vang 14K',
    stone: 'CZ xanh mint',
    weight: 2.9,
    size: ['15cm', '16cm', '17cm'],
    gender: 'Nu',
    stock: 11,
    sold: 13,
    isFeatured: false,
    status: 'active',
    description: 'Lac tay canh mo co vien da xanh nhe, de phoi voi tong mau trung tinh.'
  },
  {
    name: 'Vong co ngoc trai Velvet Pearl',
    slug: 'vong-co-ngoc-trai-velvet-pearl',
    categorySlug: 'vong-co',
    price: 7990000,
    oldPrice: 8490000,
    discount: 6,
    images: ['/images/products/choker-velvet-pearl-1.jpg', '/images/products/choker-velvet-pearl-2.jpg'],
    material: 'Ngoc trai va khoa vang',
    stone: 'Ngoc trai nuoc ngot',
    weight: 12.4,
    size: ['38cm', '40cm'],
    gender: 'Nu',
    stock: 9,
    sold: 10,
    isFeatured: true,
    status: 'active',
    description: 'Vong co ngoc trai sat co mang tinh thanh lich va sang trong.'
  },
  {
    name: 'Vong co da den Midnight Lace',
    slug: 'vong-co-da-den-midnight-lace',
    categorySlug: 'vong-co',
    price: 4290000,
    oldPrice: 4690000,
    discount: 9,
    images: ['/images/products/choker-midnight-lace-1.jpg', '/images/products/choker-midnight-lace-2.jpg'],
    material: 'Bac 925 ma rhodium',
    stone: 'Onyx den',
    weight: 6.0,
    size: ['39cm', '41cm'],
    gender: 'Nu',
    stock: 10,
    sold: 12,
    isFeatured: false,
    status: 'active',
    description: 'Mau vong co dang om nhe co mat da den tao diem nhan quyen ru.'
  },
  {
    name: 'Vong co unisex Halo Link',
    slug: 'vong-co-unisex-halo-link',
    categorySlug: 'vong-co',
    price: 3690000,
    oldPrice: 3990000,
    discount: 8,
    images: ['/images/products/choker-halo-link-1.jpg', '/images/products/choker-halo-link-2.jpg'],
    material: 'Thep khong gi',
    stone: 'Khong da',
    weight: 7.5,
    size: ['45cm', '50cm'],
    gender: 'Unisex',
    stock: 15,
    sold: 21,
    isFeatured: false,
    status: 'active',
    description: 'Vong co mat tron va day xich gon gon, hop gu unisex hien dai.'
  },
  {
    name: 'Vong co cuoi Radiant Promise',
    slug: 'vong-co-cuoi-radiant-promise',
    categorySlug: 'trang-suc-cuoi',
    price: 16900000,
    oldPrice: 17900000,
    discount: 6,
    images: ['/images/products/choker-radiant-promise-1.jpg', '/images/products/choker-radiant-promise-2.jpg'],
    material: 'Vang trang 18K',
    stone: 'Kim cuong tam',
    weight: 5.6,
    size: ['40cm', '42cm'],
    gender: 'Nu',
    stock: 6,
    sold: 9,
    isFeatured: true,
    status: 'active',
    description: 'Vong co cho ngay trong dai voi mat da trung tam va duong net mem.'
  },
  {
    name: 'Bo nhan cuoi Golden Vow',
    slug: 'bo-nhan-cuoi-golden-vow',
    categorySlug: 'trang-suc-cuoi',
    price: 18900000,
    oldPrice: 19900000,
    discount: 5,
    images: ['/images/products/wedding-golden-vow-1.jpg', '/images/products/wedding-golden-vow-2.jpg'],
    material: 'Vang 18K',
    stone: 'Kim cuong tam',
    weight: 6.4,
    size: ['14', '15', '16', '17', '18'],
    gender: 'Unisex',
    stock: 7,
    sold: 8,
    isFeatured: true,
    status: 'active',
    description: 'Bo nhan cuoi doi thiet ke co dien, be mat sang va de deo lau dai.'
  },
  {
    name: 'Bong tai cuoi Crystal Veil',
    slug: 'bong-tai-cuoi-crystal-veil',
    categorySlug: 'trang-suc-cuoi',
    price: 6390000,
    oldPrice: 6990000,
    discount: 9,
    images: ['/images/products/wedding-crystal-veil-1.jpg', '/images/products/wedding-crystal-veil-2.jpg'],
    material: 'Vang trang 14K',
    stone: 'CZ trang',
    weight: 2.6,
    size: ['Free'],
    gender: 'Nu',
    stock: 9,
    sold: 14,
    isFeatured: false,
    status: 'active',
    description: 'Bong tai dang dai nhe, giup guong mat sang va hop vay cuoi toi gian.'
  },
  {
    name: 'Lac tay cuoi Moonlight Kiss',
    slug: 'lac-tay-cuoi-moonlight-kiss',
    categorySlug: 'trang-suc-cuoi',
    price: 7290000,
    oldPrice: 7890000,
    discount: 8,
    images: ['/images/products/wedding-moonlight-kiss-1.jpg', '/images/products/wedding-moonlight-kiss-2.jpg'],
    material: 'Vang 14K',
    stone: 'CZ trang',
    weight: 3.8,
    size: ['15cm', '16cm', '17cm'],
    gender: 'Nu',
    stock: 8,
    sold: 11,
    isFeatured: false,
    status: 'active',
    description: 'Lac tay thanh manh co duong da lien tuc, ton tay trong ngay cuoi.'
  },
  {
    name: 'Dong ho nu Rose Classic',
    slug: 'dong-ho-nu-rose-classic',
    categorySlug: 'dong-ho',
    price: 5290000,
    oldPrice: 5890000,
    discount: 10,
    images: ['/images/products/watch-rose-classic-1.jpg', '/images/products/watch-rose-classic-2.jpg'],
    material: 'Thep khong gi ma vang hong',
    stone: 'Mat xa cu',
    weight: 28,
    size: ['28mm'],
    gender: 'Nu',
    stock: 14,
    sold: 18,
    isFeatured: true,
    status: 'active',
    description: 'Dong ho mat tron nho, day luoi mem va tong mau vang hong thanh lich.'
  },
  {
    name: 'Dong ho nam Navy Chrono',
    slug: 'dong-ho-nam-navy-chrono',
    categorySlug: 'dong-ho',
    price: 6890000,
    oldPrice: 7490000,
    discount: 8,
    images: ['/images/products/watch-navy-chrono-1.jpg', '/images/products/watch-navy-chrono-2.jpg'],
    material: 'Thep khong gi',
    stone: 'Kinh khoang',
    weight: 62,
    size: ['40mm'],
    gender: 'Nam',
    stock: 11,
    sold: 17,
    isFeatured: true,
    status: 'active',
    description: 'Dong ho nam mat navy, coc so ro rang va phong cach manh me hien dai.'
  },
  {
    name: 'Dong ho unisex Silver Mesh',
    slug: 'dong-ho-unisex-silver-mesh',
    categorySlug: 'dong-ho',
    price: 4590000,
    oldPrice: 4990000,
    discount: 8,
    images: ['/images/products/watch-silver-mesh-1.jpg', '/images/products/watch-silver-mesh-2.jpg'],
    material: 'Thep khong gi',
    stone: 'Mat khoang trang',
    weight: 34,
    size: ['34mm'],
    gender: 'Unisex',
    stock: 16,
    sold: 20,
    isFeatured: false,
    status: 'active',
    description: 'Dong ho day luoi unisex gon gang, phu hop cong so va di chuyen hang ngay.'
  },
  {
    name: 'Dong ho cuoi Golden Hour',
    slug: 'dong-ho-cuoi-golden-hour',
    categorySlug: 'dong-ho',
    price: 7990000,
    oldPrice: 8590000,
    discount: 7,
    images: ['/images/products/watch-golden-hour-1.jpg', '/images/products/watch-golden-hour-2.jpg'],
    material: 'Thep khong gi ma vang',
    stone: 'Mat xa cu champagne',
    weight: 38,
    size: ['32mm'],
    gender: 'Nu',
    stock: 9,
    sold: 9,
    isFeatured: false,
    status: 'active',
    description: 'Dong ho tong vang nhe phu hop lam qua tang cuoi hoac ky niem dac biet.'
  },
  {
    name: 'Nhan kim cuong Mirage',
    slug: 'nhan-kim-cuong-mirage',
    categorySlug: 'nhan',
    price: 9990000,
    oldPrice: 10800000,
    discount: 8,
    images: ['/images/products/ring-mirage-1.jpg', '/images/products/ring-mirage-2.jpg'],
    material: 'Vang trang 18K',
    stone: 'Kim cuong tam',
    weight: 3.2,
    size: ['12', '13', '14', '15'],
    gender: 'Nu',
    stock: 9,
    sold: 13,
    isFeatured: true,
    status: 'active',
    description: 'Nhan vien da trung tam ket hop vien nho xung quanh cho do sang noi bat.'
  },
  {
    name: 'Day chuyen Ribbon Glow',
    slug: 'day-chuyen-ribbon-glow',
    categorySlug: 'day-chuyen',
    price: 3490000,
    oldPrice: 3890000,
    discount: 10,
    images: ['/images/products/necklace-ribbon-glow-1.jpg', '/images/products/necklace-ribbon-glow-2.jpg'],
    material: 'Vang 10K',
    stone: 'CZ hong',
    weight: 2.8,
    size: ['40cm', '42cm'],
    gender: 'Nu',
    stock: 18,
    sold: 23,
    isFeatured: false,
    status: 'active',
    description: 'Mat day hinh no nho phu hop qua tang sinh nhat va ky niem.'
  },
  {
    name: 'Bong tai Crescent Shine',
    slug: 'bong-tai-crescent-shine',
    categorySlug: 'bong-tai',
    price: 2790000,
    oldPrice: 3090000,
    discount: 10,
    images: ['/images/products/earring-crescent-shine-1.jpg', '/images/products/earring-crescent-shine-2.jpg'],
    material: 'Vang 10K',
    stone: 'CZ trang',
    weight: 1.7,
    size: ['Free'],
    gender: 'Nu',
    stock: 20,
    sold: 26,
    isFeatured: false,
    status: 'active',
    description: 'Dang lua liem nho, de ket hop voi nhieu mau vay va ao du tiec.'
  },
  {
    name: 'Lac tay Couple Knot',
    slug: 'lac-tay-couple-knot',
    categorySlug: 'lac-tay',
    price: 2990000,
    oldPrice: 3390000,
    discount: 11,
    images: ['/images/products/bracelet-couple-knot-1.jpg', '/images/products/bracelet-couple-knot-2.jpg'],
    material: 'Bac 925 ma vang hong',
    stone: 'Khong da',
    weight: 3.3,
    size: ['16cm', '17cm', '18cm'],
    gender: 'Unisex',
    stock: 17,
    sold: 18,
    isFeatured: false,
    status: 'active',
    description: 'Mau lac tay nut that bieu trung cho su gan ket va de lam qua tang doi.'
  },
  {
    name: 'Vong co Sapphire Mist',
    slug: 'vong-co-sapphire-mist',
    categorySlug: 'vong-co',
    price: 5890000,
    oldPrice: 6490000,
    discount: 9,
    images: ['/images/products/choker-sapphire-mist-1.jpg', '/images/products/choker-sapphire-mist-2.jpg'],
    material: 'Vang trang 14K',
    stone: 'CZ xanh sapphire',
    weight: 4.8,
    size: ['39cm', '41cm'],
    gender: 'Nu',
    stock: 10,
    sold: 12,
    isFeatured: true,
    status: 'active',
    description: 'Vong co mat oval xanh dam lam diem nhan tren nen trang phuc toi gian.'
  },
  {
    name: 'Dong ho nam Carbon Edge',
    slug: 'dong-ho-nam-carbon-edge',
    categorySlug: 'dong-ho',
    price: 7590000,
    oldPrice: 8190000,
    discount: 7,
    images: ['/images/products/watch-carbon-edge-1.jpg', '/images/products/watch-carbon-edge-2.jpg'],
    material: 'Thep khong gi phu PVD',
    stone: 'Mat carbon den',
    weight: 68,
    size: ['42mm'],
    gender: 'Nam',
    stock: 8,
    sold: 10,
    isFeatured: false,
    status: 'active',
    description: 'Dong ho tong den manh me, hop phong cach nam tinh va do ben cao.'
  }
];

export function buildProducts(categoryMap) {
  return rawProducts.map((product, index) => ({
    name: product.name,
    sku: `JA-${String(index + 1).padStart(4, '0')}`,
    slug: product.slug,
    description: product.description,
    category: categoryMap[product.categorySlug],
    price: product.price,
    oldPrice: product.oldPrice,
    discount: product.discount,
    images: product.images,
    material: product.material,
    stone: product.stone,
    weight: product.weight,
    size: product.size,
    gender: product.gender,
    stock: product.stock,
    sold: product.sold,
    isFeatured: product.isFeatured,
    status: product.status
  }));
}
